### ISSUE TITLE
Installation and Setup

### ISSUE THREAD

**Issue by DelaramRajaei** [fani-lab/ReQue#23]
This is the issue where I document my observations and installation difficulties encountered during this project.

**Comment by DelaramRajaei** [comment]
@hosseinfani 
As a result of my search and learning of IR terms, I have prepared a document that contains them. Currently, I am working on it. 

I encountered a question regarding the difference between a corpus and a dataset.  I noticed the following difference, but I wasn't sure what it meant:

_Corpus mainly appears in NLP area or application domain related to texts/documents, because of its meaning "a collection of written texts, esp. the entire works of a particular author or a body of writing on a particular subject."
In contrast, dataset appears in every application domain --- a collection of any kind of data is a dataset._

I also found this table of comparison:

| | Prototypical corpus| Prototypical dataset|

| --- | --- | --- |

| Language | unrestricted production | specific phenomenon |

| Context | wide | restricted |

| Purpose | general | research question |

Links to two websites:
https://corpuslinguisticmethods.wordpress.com/2013/12/28/corpora-versus-datasets/
https://copyprogramming.com/howto/difference-in-meaning-of-these-terms-dataset-vs-corpus#difference-in-meaning-of-these-terms-dataset-vs-corpus

Link to my document:
https://docs.google.com/document/d/1swPuzXEyx6UvmaQtjEEQIYO6LN38quJInSHY1Y5IXhY/edit?usp=sharing

**Comment by hosseinfani** [comment]
@DelaramRajaei 
thank you for the nice report. 
my only suggestion is to dump the gdoc as a word doc or pdf and attach it such that the link does not depend on your gdrive.

**Comment by DelaramRajaei** [comment]
Rough draft of the IR document
[DelaramRajaei_Information_Retrieval.pdf](https://github.com/fani-lab/ReQue/files/11435463/DelaramRajaei_Information_Retrieval.pdf)

**Comment by DelaramRajaei** [comment]
Updated IR document.
[DelaramRajaei_Information_Retrieval.pdf](https://github.com/fani-lab/ReQue/files/11446697/DelaramRajaei_Information_Retrieval.pdf)

**Comment by DelaramRajaei** [comment]
@hosseinfani 
### Installing ReQue process:
- First, I clone the ReQue repository.
- Second, I install the prerequisites.
   - Tools
      - Python 3.11.2
      - pip 22.3.1
      - conda 23.3.1
   - Libraries
      - tqdm 4.65.0
      - prettytable 3.7.0
      (These two are needed for cair)
- Third, I followed the provided command in the [Readme file](https://github.com/fani-lab/ReQue#installing) and the ReQue [Installation video](https://www.youtube.com/watch?v=Vb45ALbYfy4)
   - $> cd ReQue
   - $> conda env create -f environment.yml
   - $> conda activate ReQue
- Forth, I install anserini, following these steps:
   - Installing required extensions in VS code
      - Extension Pack for Java
      - Language Support for Java(TM) by Red Hat
    - Cloning anserini repository   
    - Building using Maven
      - mvn clean package appassembler:assemble
    - In this step, I encountered a problem regarding compiling trec_eval. I found this [link](https://github.com/castorini/pyserini/discussions/1121) which suggested to install cygwin.

There are a few questions I have:  
As I write this, I am still working on installing anserini and trec_eval. 
How to compile trec_eval using Visual Studio build tools? I installed the tool but couldn't figure out how to use it.
The trec_eval [README.windows.md](https://github.com/usnistgov/trec_eval/blob/master/README.windows.md) explains how to compile it but it doesn't mention the details and the provided link displays 404 error. 

Also, I wanted to know, if I need "cair" for adding and testing the expander in this project.

In addition, this [closed issue](https://github.com/fani-lab/ReQue/issues/1) also helped me in this process.

**Comment by hosseinfani** [comment]
@DelaramRajaei 
Awesome startup log. thank you.

- the best way is to install the cygwin and use its `make` to build `trec_eval`
- No, you don't need `cair` for now

**Comment by DelaramRajaei** [comment]
**Update the IR document:**

- IR 
   - Definition
   - Difference between IR method, system, and model

- Add IR methods 
   - Definition + common IR methods

- Vector Space Models IR method
   - Sparse and dense retrieval definition + comparison + examples

- Relevance
   - Definition + Relevance Feedback

- Word embedding
   - Definition + example

[Information Retrieval.pdf](https://github.com/fani-lab/ReQue/files/11519427/Information.Retrieval.pdf)

**Installing ReQue:**

   - Install pycharm
   - Install required packages and libraries
   - Watch the installation and setup video
   - Run ReQue but encountered an error regarding the packages and libraries

**Comment by DelaramRajaei** [comment]
@hosseinfani 

I have successfully installed and run the ReQue project.

The problem was with the NLTK library which was not properly downloaded and installed.

The following commands are:

          >>> import nltk

          >>> nltk.download("stopwords")

          >>> nltk.download("punkt")

Also, I installed the PyGaggle library.

To make sure everything is fine, I run the following commands first with only the ['generate'] operation and then with all the commands ['generate', 'search', 'evaluate', 'build'].

The results are attached.

[robust04.zip](https://github.com/fani-lab/ReQue/files/11559345/robust04.zip)

Based on the [installation video](https://www.youtube.com/watch?v=cl-U4t36Ix8), I analyzed the results; however, all the results in topics.robust04.bm25.map.dataset.csv were zero. I was wondering if something in the process was wrong or if the first query always gives the most accurate results, which seems strange to me!

I am currently working on adding the new expander.

**Comment by hosseinfani** [comment]
@DelaramRajaei 
perfect. we can discuss the result tmr :)

**Comment by DelaramRajaei** [comment]
@hosseinfani 

The problem that occurred during the running process has been fixed. 

There was a problem with the trec_eval address.

I have changed the following line in ./qe/main.py in evaluate():

`eval_cmd = '{}eval/trec_eval.9.0.4/trec_eval'.format(anserini)` >>> `eval_cmd = '{}eval/trec_eval'.format(anserini)`

The new results are attached.
[robust04.zip](https://github.com/fani-lab/ReQue/files/11579806/robust04.zip)

**Comment by hosseinfani** [comment]
@DelaramRajaei 
perfect. thanks.
Can you add a new setting in ./cmn/param.py for the address of trec_eval such that the pipeline reads the address from there like this:

https://github.com/fani-lab/ReQue/blob/1ae7580782a53a9575c4594fda15aefcce9a672f/qe/cmn/param.py#L39

https://github.com/fani-lab/ReQue/blob/1ae7580782a53a9575c4594fda15aefcce9a672f/qe/main.py#L56

**Comment by DelaramRajaei** [comment]
I cloned the latest version of the ReQue project and proceeded with the following steps to setup and run the project.

1. First I create a new environment and activate it.

```
$ conda create -n ReQue
$ conda activate ReQue
```

If you are using PyCharm, you have the option to create a new project and select Conda as the new environment with Python 3.8. This will create a new environment named after your file location.

Also, you can check the Python interpreter in PyCharm, by following these steps:
File > Settings > Project: #ProjectName > Python Interpreter 

2. Instead of using the environment.yml file, I use the requirements.txt file to install the required packages.

```
$ conda install python=3.8 -n ReQue
$ pip install -r requirements.txt   
```

If you choose to use the "conda install" command, you will encounter the following error, and you will need to manually install additional packages.

> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - pydantic==1.5
>   - wn==0.0.23
>   - community
>   - pywsd
>   - prettytable==2.1.0
>   - pyserini
>   - spacy==2.2.4
>   - tagme
>   - transformers==4.0.0
>   - tokenizers==0.9.4

3. To install Anserini, you can clone the project from the provided [link](https://github.com/hosseinfani/anserini) and follow the instructions outlined in the repository.

Install the Cygwin and use its make to build trec_eval and ndeval.

4. To install Pyserini, I followed both instructions for Development installation and Pip Installation in the provided [link ](https://github.com/castorini/pyserini/blob/master/docs/installation.md).

If you do not already have JDK 11 installed, install it via conda:

```
$ conda install -c conda-forge openjdk=11
```

Ensure that you install version 11 to avoid encountering an [error](https://github.com/castorini/anserini/issues/1814).

The pip installation would encounter [errors](https://github.com/castorini/pyserini/issues/1025) and it's better to use the development installation.

5. If you encounter any errors while running the program, you can resolve them by executing the following commands: first, use `pip uninstall pyserini` to uninstall Pyserini, and then reinstall it using `pip install pyserini`.

6. In this step you may get the following error 

> DLL load failed while importing _swigfaiss: The specified module could not be found.

It can be fixed by this command
```
$ conda install -c conda-forge faiss
```

I followed the above steps to successfully install the ReQue project, which can now be used for further tasks.
