### ISSUE TITLE
Removing anserini from the pipeline and replacing it with pyserini

### ISSUE THREAD

**Issue by DelaramRajaei** [fani-lab/ReQue#30]

**Comment by hosseinfani** [comment]
@DelaramRajaei 
- We need to create a class QuerySet, converting all types of input query sets into tsv format of qid, query. 
- QuerySet implements a reformulate([expanders]) that runs a list of expanders on the queries, in seq or parallel over queries over expanders
- The search step only reads the generated tsv files and does the search in batch in seq/parallel

**Comment by DelaramRajaei** [comment]
@hosseinfani 

Regarding this task, I've effectively eliminated Anserini from the project, and currently, the project exclusively relies on Pyserini for search and evaluation purposes. Initially, I attempted to incorporate the QuerySet class as per your suggestion, but encountered certain challenges. I realized that I only required the `query_set` variable within the `abstractqexpander` class. However, I've ensured that if we do decide to add a class for queries in the future, it can now be easily integrated. 
You can find a detailed description of the code changes in the related [issue](https://github.com/fani-lab/ReQue/issues/27#issuecomment-1675680039).

**Comment by hosseinfani** [comment]
@DelaramRajaei 
perfect! thank you. so, we can safely remove the anserini installation from the readme then. right?

regarding the query_set class, are you available today ~3:30pm (before the weekly gathering) to go through the codes?

**Comment by hosseinfani** [comment]
@DelaramRajaei 
if this task is done, please close it.
